language: bash

services:
  - docker

env:
  global:
    - LINT_IMAGE=lint
    - LINT_IMAGE_011=lint-011

install:
  - docker build -t ${LINT_IMAGE} -f tests/Dockerfile .
  - docker build -t ${LINT_IMAGE_011} -f tests_011/Dockerfile .

script:
  # - docker run --rm -ti --entrypoint terraform ${LINT_IMAGE} fmt -check=true ./
  - |
    find . \
      -not -path '*/\.*' \
      -not -path './modules/consul/*' \
      -not -path './modules/vault/*' \
      -not -path './vendor/*' \
      -type f -iname '*.tf' \
      -printf '%h\n' | sort | uniq | xargs -I{} bash -c "echo {} && docker run --rm --entrypoint terraform ${LINT_IMAGE_011} fmt -check=true {}  && docker run --rm ${LINT_IMAGE_011} {}"
  - |
    for module in "./modules/consul" "./modules/vault"; do \
      echo "${module}" \
      && docker run --rm --entrypoint terraform ${LINT_IMAGE} fmt -check=true "${module}" \
      && docker run --rm ${LINT_IMAGE} "${module}"; \
      done

branches:
  only:
  - master

notifications:
  email: false
