# See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#schedule
schedule: "${schedule}"

${ttl_seconds != "" ? "ttlSecondsAfterFinished: ${ttl_seconds}" : "ttlSecondsAfterFinished: null"}

serviceAccount: ${service_account}

image:
  repository: ${image}
  tag: ${tag}
  pullPolicy: ${pull_policy}

consul:
  address: ${consul_address}
  tls:
    enabled: ${tls_enabled}
    cacert: ${tls_cacert}

nodeSelector: ${node_selector}

tolerations: ${tolerations}

affinity: ${affinity}

gcs:
  bucket: ${gcs_bucket}
  prefix: ${gcs_prefix}
  serviceAccountKey: ${service_account_key}

env: ${env}

annotations:
  serviceAccount: ${service_account_annotations}
