# See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#schedule
schedule: "${schedule}"

${ttl_seconds != "" ? "ttlSecondsAfterFinished: ${ttl_seconds}" : "ttlSecondsAfterFinished: null"}

serviceAccount: ${service_account}

image:
  repository: ${image}
  tag: ${tag}
  pullPolicy: ${pull_policy}

nodeSelector: ${node_selector}

tolerations: ${tolerations}

affinity: ${affinity}

vault:
  enabled: ${enable_vault_agent}
  pullPolicy: IfNotPresent
  address: ${vault_address}
  # PEM encoded CA used to issue Vault's Certificate
  ca: ${vault_ca}
  auth:
    path: ${vault_auth_path}
    role: ${vault_auth_role}
  gcp:
    path: ${vault_gcp_path}
  env: []

env: ${env}

entrypoint: ${entrypoint}

annotations:
  serviceAccount: ${service_account_annotations}
